workspace = { members = [ "pytube_wrpr", "yt_download_manager","yt_service", "yt_web", "yttest"] }
[package]
name = "yt_downlaoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
